export const ErrorStatusCodes = {
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  AUTHORIZATION_EXPIRED: 'AUTHORIZATION_EXPIRED',
  MISSING_PARAMETERS: 'MISSING_PARAMETERS',

  // 用户
  NAME_OR_PASSWORD_ERROR: 'NAME_OR_PASSWORD_ERROR',
  NAME_ALREADY_EXSIT: 'NAME_ALREADY_EXSIT',

  // 标签
  TAG_IS_USED: 'TAG_IS_USED',
}
